### ISSUE TITLE
timezone api

### ISSUE THREAD

**Issue by oblonski** [graphhopper/timezone#1]
Also wenn google das als api anbietet, sollten wir das nicht auch überlegen? Die machen ja meistens Dinge nicht einfach so ;). Ansonsten überlegen ob wir das Open Source machen?

**Comment by karussell** [comment]
Klar. Wir können ja beides. Also Open Source und als API :) ?

**Comment by karussell** [comment]
sorry ich musste da den titel ändern ;)

**Comment by oblonski** [comment]
Klingt gut. Das machen wir so. Dann mach ich daraus einfach mal gleich ein public rep. Oder?

**Comment by karussell** [comment]
Then we have to switch to English :)

**Comment by karussell** [comment]
Boah, diese neuen Farben bei github sind voll agro.
